## 1. Finding the sum of array elements

In [15]:
def sum1(arr):
    result = 0
    for x in arr:
        result += x
    return result

arr = map(int,input().split())
print('sum of array:',sum1(arr))

2 4 6 8 0
sum of array: 20


In [16]:
def sum2(arr):
    result = sum(arr)
    return result

arr = map(int,input().split())
print('sum of array:',sum2(arr))

2 4 6 8 0
sum of array: 20


In [17]:
print(sum2(map(int,input().split())))

2 4 6
12


In [18]:
print(sum(map(int,input().split())))

2 4 6
12


## 2. Python program to find a series in an array consisting of characters

In [21]:
def seri(char):
    for i in range(len(char)-2):
        if char[i]=='a' and char[i+1]=='b' and char[i+2]=='c':
            return True
    return False

print(seri(['x','a','y','z','a','b','c']))

True


## 3. program to find the occurrence of a particular number in an array

In [25]:
def occur(array):
    count = 0
    for n in array:
        if n == find:
            count = count + 1
    return count

num = map(int,input().split())
find = int(input())
print(occur(num))

2 2 2 2 2 2 4 4 5 5 6 78
2
6


In [29]:
def occur(array):
    count = 0
    for num in array:
        if num == 3:
            count = count + 1
    return count

print(occur(array=map(int,input('enter elements:').split())))

enter elements:3 3 3 3 3  5 5 5
5


## 4. Python program to find the largest element in an array

In [18]:
def find(n,arr):
    max_val = arr[0]
    for i in range(1,n):
        if arr[i]>max_val:
            max_val = arr[i]
    return max_val
        

n = int(input('Enter number of elements in an array:'))
arr = []
print('Enter elements of array')

for i in range(n):
    numbers = int(input())
    arr.append(numbers)

max_val = find(n, arr)
print('Largest Number in given array:',max_val)

Enter number of elements in an array:5
Enter elements of array
23
45
23
89
65
Largest Number in given array: 89


In [35]:
def largest(elements):
    x=max(elements)
    return x

elements = map(str,input().split())
largest(elements)

2 3 4 5 6 7


'7'

In [37]:
print(max(map(str,input().split())))

2 3 4 5 6 7 8
8


## 5. program for array rotation

In [50]:
from collections import deque
array = deque(list(map(str,input('enter array elements: '))))
array.rotate(3)
print(array)

enter array elements: 1 2 3 4 5 6 7 8 9 0
deque(['9', ' ', '0', '1', ' ', '2', ' ', '3', ' ', '4', ' ', '5', ' ', '6', ' ', '7', ' ', '8', ' '])


In [45]:
array = deque([2,3,4,5,6,7,8])
array.rotate(2)
print(array)

deque([7, 8, 2, 3, 4, 5, 6])


In [ ]:
## 6. 

## 7. Find the union and intersection of two arrays

In [53]:
a = list(map(int,input('Enter Elements of 1st List:').split()))
b = list(map(int,input('Enter Elements of 2nd List:').split())) 

print('union:',set(a) | set(b))
print('Intersection:',set(a) & set(b))

print('Difference:',set(a) - set(b))
print('Symmetric Difference:',set(a) ^ set(b))

Enter Elements of 1st List:15 9 10 56 23 78 5 4 9
Enter Elements of 2nd List:9 4 5 36 47 26 10 45 87
union: {4, 5, 36, 9, 10, 45, 78, 15, 47, 87, 23, 56, 26}
Intersection: {9, 10, 4, 5}
Difference: {56, 23, 78, 15}
Symmetric Difference: {36, 45, 78, 47, 15, 23, 87, 56, 26}


## 8. program to create matrix in Python

In [56]:
mat = [[4,6,8,3,5,7],[6,9,2,9,3,8],[2,5,2,6,9,8],[4,5,6,5,1,3]]

for i in range(4):
    for j in range(6):
        print(mat[i][j],end=' ')
    print()

4 6 8 3 5 7 
6 9 2 9 3 8 
2 5 2 6 9 8 
4 5 6 5 1 3 


## 9. program to create matrix using numpy

In [78]:
import numpy as np
mat1 = np.array([[16,21,37],[74,45,46],[17,88,29]])
print('Method 1:\n',mat1)
mat2 = np.matrix("17,21,32;43,59,62;70,82,91")
print('Method 2:\n',mat2)

Method 1:
 [[16 21 37]
 [74 45 46]
 [17 88 29]]
Method 2:
 [[17 21 32]
 [43 59 62]
 [70 82 91]]


## 10. program for matrix operations

In [85]:
print('Addition:\n',mat1+mat2)
print('Subtraction:\n',mat1-mat2)
print('Division:\n',mat1/mat2)
print('Multiplication:\n',mat1*mat2)
print('Product:\n',np.dot(mat1,mat2))
print('Square Root:\n',np.sqrt(mat1))
print('Square Root:\n',np.sqrt(mat2))

Addition:
 [[ 33  42  69]
 [117 104 108]
 [ 87 170 120]]
Subtraction:
 [[ -1   0   5]
 [ 31 -14 -16]
 [-53   6 -62]]
Division:
 [[0.94117647 1.         1.15625   ]
 [1.72093023 0.76271186 0.74193548]
 [0.24285714 1.07317073 0.31868132]]
Multiplication:
 [[3765 4609 5181]
 [6413 7981 9344]
 [6103 7927 8639]]
Product:
 [[3765 4609 5181]
 [6413 7981 9344]
 [6103 7927 8639]]
Square Root:
 [[4.         4.58257569 6.08276253]
 [8.60232527 6.70820393 6.78232998]
 [4.12310563 9.38083152 5.38516481]]
Square Root:
 [[4.12310563 4.58257569 5.65685425]
 [6.55743852 7.68114575 7.87400787]
 [8.36660027 9.05538514 9.53939201]]


## 11. program to get matrix as input from user and print it in different type

In [63]:
t=()
rows = int(input('Enter Number of Rows:'))
cols = int(input('Enter Number of Columns:'))

for i in range(rows):
    c=()
    for j in range(cols):
        v = int(input())
        c += (v,)
    t +=(c,)

print('Method 1')
for i in range(len(t)):
    for j in range(len(t[i])):
        print(t[i][j],end=' ')
    print()

print('Method 2')
for x in t:
    for y in x:
        print(y,end=' ')
    print()

print('Method 3')
print(t)

Enter Number of Rows:2
Enter Number of Columns:3
1
2
3
4
5
6
Method 1
1 2 3 
4 5 6 
Method 2
1 2 3 
4 5 6 
Method 3
((1, 2, 3), (4, 5, 6))


## 12. program to add two matrices and print the resulting matrix

In [36]:
mat1 = ()
mat2 = ()
add = ()
rows = int(input('Enter Number of Rows:'))
cols = int(input('Enter Number of Columns:'))

print('Matrix 1')
for i in range(rows):
    c=()
    for j in range(cols):
        v = int(input('Enter Value {}.{}:'.format(i,j)))
        c += (v,)
    mat1 += (c,)

print('Matrix 2')
for i in range(rows):
    c=()
    for j in range(cols):
        v = int(input('Enter Value {}.{}:'.format(i,j)))
        c += (v,)
    mat2 += (c,)

for i in range(rows):
    c=()
    for j in range(cols):
        v=mat1[i][j]+mat2[i][j]
        c += (v,)
    add += (c,)

print(mat1)
print(mat2)
print('Addition',add)

Enter Number of Rows:2
Enter Number of Columns:2
Matrix 1
Enter Value 0.0:12
Enter Value 0.1:34
Enter Value 1.0:56
Enter Value 1.1:78
Matrix 2
Enter Value 0.0:90
Enter Value 0.1:34
Enter Value 1.0:56
Enter Value 1.1:78
((12, 34), (56, 78))
((90, 34), (56, 78))
Addition ((102, 68), (112, 156))


## 13. program to filter matrix based on a condition

In [43]:
students = (('Akshay',21),('Bunny',30),('GB',25),('Gore',35))
print('Students',students)

select=()
for s in students:
    if (s[1] >= 25):
        select += (s,)

print('Students Selected:',select)   

Students (('Akshay', 21), ('Bunny', 30), ('GB', 25), ('Gore', 35))
Students Selected: (('Bunny', 30), ('GB', 25), ('Gore', 35))


## 14. program to illustrate the working of lambda functions on array

In [64]:
marks = [80,76,97,45,67,78,35,32]
stud = lambda:['First' if (per>=75 and per<=100) else 'Second' if (per>=50 and per <=49) else 'Fail' for per in marks]
print(stud())

['First', 'First', 'First', 'Fail', 'Fail', 'First', 'Fail', 'Fail']


## 15. program to apply lambda functions on array

In [9]:
#using function
def cel_to_feh(c):
    f=9/5*c+32
    return f

celsius = [12,45,6,78,5,26,67]
print('Temp. in Celsius:',celsius)

fah_temp=[]
for t in celsius:
    x = cel_to_feh(t)
    fah_temp.append(x)
print('Temperature in Fahrenheit:',fah_temp)

Temp. in Celsius: [12, 45, 6, 78, 5, 26, 67]
Temperature in Fahrenheit: [53.6, 113.0, 42.8, 172.4, 41.0, 78.80000000000001, 152.60000000000002]


In [10]:
#using lambda
celsius = [12,45,6,78,5,26,67]
print('Temp. in Celsius:',celsius)

fah_temp = list(map(lambda c:9/5*c+32, celsius))
print('Temperature in Fahrenheit:',fah_temp)

Temp. in Celsius: [12, 45, 6, 78, 5, 26, 67]
Temperature in Fahrenheit: [53.6, 113.0, 42.8, 172.4, 41.0, 78.80000000000001, 152.60000000000002]
